# Generated by Django 6.0 on 2026-02-24 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kirti', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='Contact',
        ),
    ]
